set(VCPKG_TARGET_ARCHITECTURE wasm32)
set(VCPKG_CMAKE_SYSTEM_NAME Emscripten)

set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CRT_LINKAGE static)

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "$ENV{EMSCRIPTEN_TOOLCHAIN_FILE}")

set(VCPKG_BUILD_TYPE release)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE
        "${CMAKE_CURRENT_LIST_DIR}/../../emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake")